### ISSUE TITLE
如何在 JS 中调用刷新数据去重新绘制图标？有没有接口？

### ISSUE THREAD

**Issue by my9074** [wangshijun/angular-echarts#10]

**Comment by wangshijun** [comment]
angular 的 data binding 机制能自动处理这种情况吧？

**Comment by my9074** [comment]
好像没有吧？我按你给的 DEMO 把 $scope.data 变了 ，它没有自动重新绘图

**Comment by my9074** [comment]
@wangshijun 
我看了下你写的 angular-echarts.js，只有在自定义指令初始化 link 的时候调用了 getLinkFunction 函数，在那里面进行了绘图。别的地方并没有监听数据的变化重新调用 setOptions()

**Comment by wangshijun** [comment]
@my9074 你是对的，确实存在`bug`，我在 `v0.3.1` 中修复了这个问题，详见 `docs` 下面的示例。需要注意的是，在 `angular` 的 `scope` 外部改变 `data` 或者 `config`，可能会无法按预期刷新，但这个是 `angular` 的工作机制。注意 `$interval` 的使用就行了。

**Comment by wangshijun** [comment]
@my9074 请下载最新版尝试下，如果解决了问题，我就可以关闭这个 `Issue` 了

**Comment by my9074** [comment]
OK ~ 可以了～辛苦了

**Comment by wangshijun** [comment]
哈哈，很高兴这个包能够帮到你！
