### ISSUE TITLE
希望添加 radar 图的 directive

### ISSUE THREAD

**Issue by wegramm** [wangshijun/angular-echarts#11]
谢谢!

**Comment by wangshijun** [comment]
v0.3.2 中增加了 `radar` 图，需要配置 `config.polar` 和 `data`，详见 `docs` 目录下的实例。#11

**Comment by my9074** [comment]
radar 貌似有 BUG， 给的 DEMO 里，浏览器报 : 

![2015-10-19 10 39 30](https://cloud.githubusercontent.com/assets/4555635/10569423/730ffd92-7658-11e5-9306-82a0e5213ffb.png)

**Comment by wegramm** [comment]
多谢!
目前只经过简单测试, 但是我这儿是能跑的

![screenshot from 2015-10-20 17 21 02](https://cloud.githubusercontent.com/assets/13952192/10611960/f7e4e482-774e-11e5-8b00-cb90ca6ae27f.png)
