### ISSUE TITLE
不提供图表自适应吗？ 

### ISSUE THREAD

**Issue by huguangju** [wangshijun/angular-echarts#13]
https://github.com/wangshijun/angular-echarts/blob/master/src/directive.js#L21

必须指定宽度，不指定则默认为320px, 这样不太妥吧。

**Comment by wangshijun** [comment]
我会尽快加上宽度自适应的功能，之前写的简单没考虑这些。

**Comment by wangshijun** [comment]
已经增加自动宽度，请尝试最新版，具体见 commit：bee2dc2

**Comment by huguangju** [comment]
多谢

**Comment by zxkane** [comment]
是会自动根据外部div大小来调整chart大小吗？

试用了`index.html`中的图表，调整窗口大小，图表大小并没有响应变化。是有特性参数需要指定吗？看了commit bee2dc2, 感觉应该是会自动调整的阿。

**Comment by huguangju** [comment]
@zxkane 这个issue的标题让你误解了，这里讨论的是初始化时宽度自适应（撑满父容器），你说的是echarts图表根据屏幕大小调整自适应。

在setOption后加上下边一句就可以：  
 `window.onresize = myChart.resize;`  

> 在本项目中尝试不生效，原因不明，但在我实际的项目中是OK的

参考： ecomfe/echarts#1414
http://www.oschina.net/question/2309867_223990

**Comment by wangshijun** [comment]
@huguangju @zxkane 目前的自适应实现只是在初始化的时候自动获取容器的宽高，至于窗口或者容器元素的后续大小变化，需要自己在外层做下兼容。

**Comment by Tedko** [comment]
![2016-01-26 4 35 11](https://cloud.githubusercontent.com/assets/6687437/12599955/cd0016a8-c44a-11e5-93d5-d693c025a4c9.png)
上图是echart angular，下图是 highchart
宽度为什么没有撑满父容器呢

**Comment by yy7054wyq5** [comment]
正确的使用方式
window.onresize = function () {
            myChart.resize();
          };
