### ISSUE TITLE
能不能适配一下手机端？

### ISSUE THREAD

**Issue by wwgc** [wangshijun/angular-echarts#20]
页面端很漂亮。手机上，文字都挤在一起了。能不能适配一下？

**Comment by wangshijun** [comment]
哦，还没测试过echarts在手机端性能如何，我先建立1个里程碑，到时候会支持

**Comment by orangebook** [comment]
我解决了，主要添加windows.onsize = function(){}中，针对echart容器的宽高进行适配。
[这位哥们已经完成了针对窗口的适配](http://blog.csdn.net/u012043416/article/details/51912011)。

**Comment by orangebook** [comment]
将该代码封装进ng，基本就OK了，对移动端也是同里
