### ISSUE TITLE
Does it works with eCharts 3?

### ISSUE THREAD

**Issue by gudh** [wangshijun/angular-echarts#24]
Hi, thanks for building this amazing directive!

Can you specify the eCharts version that angular-echarts require?

Does it works with 3.x? or just work with 2.x?

Thanks!

**Comment by jingzhou123** [comment]
请问你试了吗？现在我打算用echarts3，兼容吗？

**Comment by Tedko** [comment]
same question here

**Comment by gudh** [comment]
well, it doesn't, so I wrote my own simple version: https://github.com/gudh/ngecharts

**Comment by Tedko** [comment]
great thx
