### ISSUE TITLE
画双轴条形图时，xAxisIndex设置后无效

### ISSUE THREAD

**Issue by yangziwen** [wangshijun/angular-echarts#25]
你好，非常感谢你提供的angular整合echarts的方案和实现。

目前我在画横向双轴条形图的时候，遇到了设置xAxisIndex=1后不起作用的问题，请问如何解决？

在别的场景下使用yAxisIndex不存在这样的问题。

**Comment by yangziwen** [comment]
找到原因了，好像yAxisIndex有效，也是别人改过代码的结果

**Comment by wangshijun** [comment]
好的，那就关闭此问题
