### ISSUE TITLE
echarts 3.0

### ISSUE THREAD

**Issue by talatbaig** [wangshijun/angular-echarts#28]
Hi,

When will you release echarts 3.0 support

**Comment by crissmoldovan** [comment]
+1

**Comment by HelloJasonZhang** [comment]
I have created a pull request to support echarts3.0. Hopefully the author can pull my code.

**Comment by wangshijun** [comment]
https://github.com/wangshijun/angular-echarts/releases/tag/v1.0.0，please try v1.0.0, feedback are welcomed!
