### ISSUE TITLE
npm bower latest  version inconsistency (0.3.5 vs 0.3.6)

### ISSUE THREAD

**Issue by akkumar** [wangshijun/angular-echarts#52]
Tried to install angular-echarts through bower for 0.3.6 . 

bower angular-echarts#0.3.6     ENORESTARGET No tag found that was able to satisfy 0.3.6

Additional error details:
Available versions in https://github.com/wangshijun/angular-echarts.git: 0.3.5, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.2, 0.2.1, 0.2.0, 0.2.0, 0.1.26, 0.1.25, 0.1.21, 0.1.20, 0.1.19, 0.1.18, 0.1.17, 0.1.16, 0.1.15, 0.1.14, 0.1.13, 0.1.12, 0.1.11, 0.1.10, 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1

Aliter: the latest version on npm seems to 0.3.6 though. 

https://www.npmjs.com/package/angular-echarts . 

It would be great to have the latest version consistently in either of them though. Thanks !

**Comment by wangshijun** [comment]
https://github.com/wangshijun/angular-echarts/releases/tag/v1.0.0，please try v1.0.0, feedback are welcomed!
