### ISSUE TITLE
中国地图怎么显示数据

### ISSUE THREAD

**Issue by bluecitymoon** [wangshijun/angular-echarts#53]
类似这个页面的？http://echarts.baidu.com/gallery/editor.html?c=doc-example/scatter-visualMap-piecewise

从源代码看，将配置和数据做了分离并用统一的格式来处理，但把地图数据放到data的series里并没有显示。可否提供另外一个选项使用官方格式的配置？

![image](https://cloud.githubusercontent.com/assets/248692/23203151/3b140332-f91c-11e6-9948-8cab4987c869.png)

**Comment by wangshijun** [comment]
https://github.com/wangshijun/angular-echarts/releases/tag/v1.0.0，please try v1.0.0, feedback are welcomed!

**Comment by bluecitymoon** [comment]
@wangshijun will try, thanks for your great work!
