### ISSUE TITLE
Dependency on angular ~1.3 warranted ? 

### ISSUE THREAD

**Issue by akkumar** [wangshijun/angular-echarts#54]
In bower.json - I see a dependency on angular 1.3 .
    "angular": "~1.3",

I am using angular 1.5.9 and things look ok to me.  Is there a reason for the 1.3 dependency or can it be broadly 1.3+ , as in : 

    "angular": ">=1.3",

Any thoughts ?

**Comment by wangshijun** [comment]
I have tried your suggestion, several issues reported:

console error thrown;
map chart not working;

**Comment by wangshijun** [comment]
https://github.com/wangshijun/angular-echarts/releases/tag/v1.0.0，please try v1.0.0, feedback are welcomed!
