### ISSUE TITLE
Dependency on echarts 2.2.7 warranted 

### ISSUE THREAD

**Issue by akkumar** [wangshijun/angular-echarts#55]
bower.json contains this:
    "echarts": "~2.2.7"
indicating this directive is compatible with the minor versions.

I am using echarts 3.4.0 though and things seem ok. So - is this compatibility on minor versions warranted or any known incompatibility issues with echarts 3.x that prevents it from being: 
    "echarts": ">=2.2.7"

**Comment by wangshijun** [comment]
I have tried your suggestion, several issues reported:

* console error thrown;
* map chart not working;

**Comment by akkumar** [comment]
That would be an issue with echarts version compatibility ( between 2.2.7 vs 3.4.0) or angularjs as in #54 ? 

If indeed this directive is incompatible with echarts 3.x , is there any version variable in echarts or similar that we can use to make this directive compatible with the latest version of echarts ( as also being backward compatible ) ?

**Comment by wangshijun** [comment]
https://github.com/wangshijun/angular-echarts/releases/tag/v1.0.0，please try v1.0.0, feedback are welcomed!
