### ISSUE TITLE
Echarts need to update version number in bower configuration file

### ISSUE THREAD

**Issue by bluecitymoon** [wangshijun/angular-echarts#57]
Hi @wangshijun 
Great update since the latest change. There is a small issue that the version number should be changed in the bower configuration file:
https://github.com/wangshijun/angular-echarts/blob/master/bower.json

![image](https://cloud.githubusercontent.com/assets/248692/23463594/0aeac9d2-fecd-11e6-9309-c90b92c42fb2.png)

I manually download the echarts 3.0 from baidu and the 1.0.0 version looks really great. Thanks for your nice contribution! Great job.

**Comment by wangshijun** [comment]
Thanks for you advice, now v1.0.1 is avaliable, 😄

**Comment by bluecitymoon** [comment]
@wangshijun Thanks!
