### ISSUE TITLE
哪里有使用文档？

### ISSUE THREAD

**Issue by iamwelk** [wangshijun/angular-echarts#64]
没有找到使用文档啊，只有简单的几个样例。哪里有比较完整的文档吗？
样例里面的配置太少了啊。。

**Comment by Cancybabe** [comment]
同求文档。

**Comment by wangshijun** [comment]
项目内的文档参照：`docs/index.html`，请更多参照百度官方的文档。

此外，https://github.com/wangshijun/angular-echarts/pull/73 merge 之后，能完全按照百度官方的配置去写。

**Comment by liwenda122** [comment]
ng1.x 没必要封装echart组件，做了反而是画蛇添足 性能很差
